[DGODP-337]
discovery-digital/jsonschema pull request #11
Opened 2018-05-03 08:02 UTC by annaleskiv

added floatKeywords and fixed tests

2018-05-03 09:22 UTC, bunyk commented on reflect_test.go
> +	return expectedJSON
I would suggest to do it like this, will be less brittle:
```
func sanitazeExpectedJson(expectedJSON []byte) []byte {
	var js interface{}
	json.Unmarshal(expectedJSON, &js)
	clean, _ := json.Marshal(js)
	return clean
}
```

2018-05-03 09:43 UTC, bunyk approved these changes

2018-05-04 00:53 UTC, welps requested changes
Implement @bunyk's comment and fix spelling 

sanitaze = sanitize

2018-05-04 11:06 UTC, annaleskiv commented
all fixed

2018-05-07 05:43 UTC, welps approved these changes

2018-05-07 05:43 UTC, merged